import { Link } from "react-router-dom";
import { SEO, pageSEO } from "../components/SEO";
import { products } from "../data/products";

const productCopy: Record<string, { label: string; title: string; text: string; points: string[] }> = {
  gridguard: { label: "For electricity providers", title: "Know where electricity and revenue are being lost.", text: "GridGuard helps utility teams find unusual energy use, understand loss hotspots and decide where to act first.", points: ["See loss hotspots", "Prioritize field work", "Track cases and results"] },
  "edn-light": { label: "For electricity customers", title: "Make everyday electricity services easier.", text: "EDN Light gives customers one clear place to manage a meter, view usage, buy electricity and follow every transaction.", points: ["View meter activity", "Buy or send electricity", "Keep tokens and receipts"] },
  asteria: { label: "For product and research teams", title: "Test new energy technology without risking a live network.", text: "Asteria is a digital city where teams can run repeatable grid and meter scenarios, test integrations and measure results safely.", points: ["Simulate grid events", "Create test data", "Measure system performance"] },
  "bankable-data-exchange": { label: "For GenCos and funders", title: "Turn generation records into clearer investment decisions.", text: "Bankable Data Exchange brings operating, payment and evidence records together to explain performance and finance readiness.", points: ["Connect evidence", "See energy-to-cash performance", "Prepare finance-ready reports"] },
  core: { label: "For energy companies and app builders", title: "Help energy systems share information.", text: "EDN Core gives companies and apps a safe, common way to connect and use energy information.", points: ["Use the same clear format", "Control who can connect", "Build connected apps"] },
};

const primary = "inline-flex h-12 items-center justify-center rounded-lg bg-[#18c795] px-7 text-sm font-bold text-[#071522] transition hover:bg-[#13b78a]";
const darkButton = "inline-flex h-12 items-center justify-center rounded-lg bg-[#071522] px-7 text-sm font-bold text-white transition hover:bg-[#10263a]";
const outline = "inline-flex h-12 items-center justify-center rounded-lg border border-slate-300 px-7 text-sm font-bold text-slate-900 transition hover:border-slate-500 hover:bg-white";

export const Home = () => <div className="bg-white text-slate-950">
  <SEO {...pageSEO.home} />

  <section className="relative overflow-hidden bg-[#edf7f3]"><div className="absolute -right-32 -top-48 h-[560px] w-[560px] rounded-full bg-[#18c795]/15 blur-3xl" /><div className="container relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-20 sm:px-6 md:py-28 lg:grid-cols-[0.9fr_1.1fr] lg:py-32">
    <div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Energy Data Network</p><h1 className="mt-5 max-w-2xl text-4xl font-black leading-[1.08] tracking-tight sm:text-5xl lg:text-[3.75rem]">Better energy decisions start with clear data.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">We build simple digital products for the people who produce, deliver, use and finance energy.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/products" className={primary}>Explore our products</Link><Link to="/contact?product=General%20inquiry" className={outline}>Contact EDN</Link></div></div>
    <div className="relative"><div className="absolute inset-8 rounded-full bg-[#18c795]/20 blur-3xl" /><img src="/images/products/core.jpg" alt="Connected energy systems powered by EDN" className="relative aspect-[4/3] w-full rounded-[2rem] object-cover shadow-2xl shadow-slate-900/15" /></div>
  </div></section>

  <section className="border-y border-slate-200 bg-white"><div className="container mx-auto flex max-w-7xl gap-2 overflow-x-auto px-5 py-5 sm:px-6">{products.map((product) => <a key={product.slug} href={`#${product.slug}`} className="whitespace-nowrap rounded-full border border-slate-200 px-5 py-2.5 text-sm font-bold text-slate-700 transition hover:border-emerald-500 hover:text-emerald-700">{product.name}</a>)}</div></section>

  <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-5 sm:px-6"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">What we build</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-4xl md:text-5xl">Five products. Five clear energy problems.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Choose the product that matches what you need to improve.</p></div></div></section>

  {products.map((product, index) => { const copy = productCopy[product.slug]; const reversed = index % 2 === 1; return <section id={product.slug} key={product.slug} className={index % 2 === 0 ? "bg-[#f5f8f7] py-20 md:py-28" : "bg-white py-20 md:py-28"}><div className="container mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-6 lg:grid-cols-2 lg:gap-20"><div className={reversed ? "lg:order-2" : ""}><img src={product.image} alt={`${product.name} product illustration`} className="aspect-[4/3] w-full rounded-[1.75rem] object-cover shadow-xl shadow-slate-900/10" loading="lazy" /></div><div className={reversed ? "lg:order-1" : ""}><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">{copy.label}</p><p className="mt-3 text-sm font-bold text-slate-500">{product.name}</p><h2 className="mt-4 max-w-xl text-3xl font-black leading-tight sm:text-4xl">{copy.title}</h2><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">{copy.text}</p><ul className="mt-7 grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{copy.points.map((point) => <li key={point} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><span className="material-symbols-outlined text-xl text-emerald-600">check_circle</span>{point}</li>)}</ul><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to={`/products/${product.slug}`} className={darkButton}>Explore {product.name}</Link><Link to={`/contact?product=${encodeURIComponent(product.name)}`} className={outline}>Contact us</Link></div></div></div></section>; })}

  <section className="bg-[#071522] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-5 sm:px-6"><div className="grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#18c795]">Getting started</p><h2 className="mt-4 text-3xl font-black leading-tight sm:text-4xl">Start with one problem.</h2><p className="mt-4 max-w-md leading-7 text-slate-300">You do not need to understand every EDN product. Tell us what you need to improve.</p></div><ol className="grid gap-8 md:grid-cols-3">{[["01", "Describe the problem", "Tell us what is difficult today and who it affects."], ["02", "Find the right product", "We match the need to the most useful EDN product."], ["03", "Define a first step", "Together, we outline the data, users and result to test."]].map(([number, title, text], index) => <li key={number} className="relative border-t border-white/20 pt-6">{index < 2 && <span className="absolute -right-4 -top-3 hidden h-6 w-6 items-center justify-center rounded-full bg-[#18c795] text-[#071522] md:flex"><span className="material-symbols-outlined text-sm">arrow_forward</span></span>}<span className="text-sm font-black text-[#18c795]">{number}</span><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></li>)}</ol></div></div></section>

  <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-5 sm:px-6"><div className="overflow-hidden rounded-[2rem] bg-[#18c795] px-7 py-12 text-[#071522] md:flex md:items-center md:justify-between md:gap-10 md:px-14 md:py-16"><div><h2 className="max-w-2xl text-3xl font-black leading-tight sm:text-4xl">What energy problem are you trying to solve?</h2><p className="mt-4 max-w-xl text-lg text-[#0b4639]">Tell us in plain language. We will help you find the right place to start.</p></div><Link to="/contact?product=General%20inquiry" className="mt-8 inline-flex h-12 shrink-0 items-center justify-center rounded-lg bg-[#071522] px-8 text-sm font-bold text-white hover:bg-[#10263a] md:mt-0">Talk to EDN</Link></div></div></section>
</div>;
