import { Link } from "react-router-dom";
import { SEO, pageSEO } from "../components/SEO";
import { products } from "../data/products";

export const Products = () => <div className="bg-white pb-24 text-slate-950">
  <SEO {...pageSEO.products} />
  <section className="bg-[#edf7f3]"><div className="container mx-auto max-w-7xl px-5 py-20 sm:px-6 md:py-28"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Our products</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-tight sm:text-5xl">Simple tools for real energy problems.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Find the product that matches what you need to improve.</p></div></section>
  <section className="container mx-auto max-w-7xl px-5 py-20 sm:px-6"><div className="grid gap-x-8 gap-y-14 md:grid-cols-2">{products.map((product) => <article key={product.slug}><Link to={`/products/${product.slug}`} className="group block overflow-hidden rounded-2xl"><img src={product.image} alt={`${product.name} illustration`} className="aspect-[16/10] w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></Link><div className="pt-6"><div className="flex flex-wrap items-center gap-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">{product.category}</p><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">{product.status}</span></div><h2 className="mt-3 text-2xl font-black">{product.name}</h2><p className="mt-3 max-w-xl text-lg font-semibold text-slate-800">{product.headline}</p><p className="mt-3 max-w-xl leading-7 text-slate-600">{product.summary}</p><div className="mt-6 flex flex-wrap gap-5"><Link to={`/products/${product.slug}`} className="inline-flex items-center gap-2 font-bold text-emerald-700">View product <span className="material-symbols-outlined text-lg">arrow_forward</span></Link><Link to={`/contact?product=${encodeURIComponent(product.name)}`} className="font-bold text-slate-600 hover:text-slate-950">Contact us</Link></div></div></article>)}</div></section>
  <section className="container mx-auto max-w-7xl px-5 sm:px-6"><div className="rounded-[2rem] bg-[#18c795] px-8 py-12 text-center text-[#071522] md:px-14"><h2 className="text-3xl font-black">Not sure which product fits?</h2><p className="mx-auto mt-3 max-w-xl text-[#0b4639]">Tell us what is difficult today. We will help you find the right place to start.</p><Link to="/contact?product=Product%20advisory" className="mt-7 inline-flex h-12 items-center justify-center rounded-lg bg-[#071522] px-8 text-sm font-bold text-white">Talk to us</Link></div></section>
</div>;
