import { Link, Navigate, useParams } from "react-router-dom";
import { SEO } from "../components/SEO";
import { getProduct, products } from "../data/products";

export const ProductDetail = () => {
  const { slug } = useParams(); const product = getProduct(slug);
  if (!product) return <Navigate to="/products" replace />;
  const contact = `/contact?product=${encodeURIComponent(product.name)}`;
  return <div className="bg-white pb-24 text-slate-950"><SEO title={product.name} description={product.summary} url={`https://energydatanetwork.com/products/${product.slug}`} />
    <section className="bg-[#edf7f3]"><div className="container mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-24"><Link to="/products" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-emerald-700"><span className="material-symbols-outlined text-lg">arrow_back</span>All products</Link><div className="mt-10 grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">{product.eyebrow}</p><h1 className="mt-4 text-4xl font-black sm:text-5xl">{product.name}</h1><p className="mt-5 text-2xl font-bold leading-tight text-slate-800">{product.headline}</p><p className="mt-5 text-lg leading-8 text-slate-600">{product.summary}</p><Link to={contact} className="mt-8 inline-flex h-12 items-center rounded-lg bg-[#071522] px-7 text-sm font-bold text-white">{product.cta}</Link></div><img src={product.image} alt={`${product.name} illustration`} className="aspect-[4/3] w-full rounded-[2rem] object-cover shadow-2xl shadow-slate-900/15" /></div></div></section>
    <section className="container mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-6 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">Who it helps</p><h2 className="mt-3 text-3xl font-black">Made for the people doing the work.</h2><div className="mt-6 flex flex-wrap gap-2">{product.audience.map(x => <span key={x} className="rounded-full bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-700">{x}</span>)}</div></div><div className="grid gap-4 sm:grid-cols-2">{product.outcomes.map(x => <div key={x} className="flex gap-3 rounded-xl border border-slate-200 p-5"><span className="material-symbols-outlined text-emerald-600">check_circle</span><p className="font-semibold">{x}</p></div>)}</div></section>
    <section className="bg-[#f5f8f7] py-20"><div className="container mx-auto max-w-7xl px-5 sm:px-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">What you can do</p><h2 className="mt-3 text-3xl font-black">Everything you need in one product.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{product.capabilities.map((x,i) => <div key={x.title} className="rounded-2xl bg-white p-7 shadow-sm"><span className="text-sm font-black text-emerald-700">0{i+1}</span><h3 className="mt-4 text-xl font-bold">{x.title}</h3><p className="mt-3 leading-7 text-slate-600">{x.description}</p></div>)}</div></div></section>
    <section className="container mx-auto max-w-7xl px-5 py-20 sm:px-6"><p className="text-sm font-bold uppercase tracking-[0.16em] text-emerald-700">How it works</p><div className="mt-10 grid gap-8 md:grid-cols-3">{product.workflow.map((x,i) => <div key={x.title} className="border-t-2 border-emerald-500 pt-6"><span className="text-sm font-black text-emerald-700">STEP {i+1}</span><h3 className="mt-4 text-xl font-bold">{x.title}</h3><p className="mt-3 leading-7 text-slate-600">{x.description}</p></div>)}</div></section>
    <section className="container mx-auto max-w-7xl px-5 sm:px-6"><div className="rounded-[2rem] bg-[#18c795] px-8 py-12 text-[#071522] md:flex md:items-center md:justify-between md:gap-10 md:px-14"><div><h2 className="text-3xl font-black">Interested in {product.name}?</h2><p className="mt-3 max-w-xl text-[#0b4639]">{product.ctaNote}</p></div><Link to={contact} className="mt-7 inline-flex h-12 shrink-0 items-center rounded-lg bg-[#071522] px-8 text-sm font-bold text-white md:mt-0">Contact us</Link></div></section>
    <section className="container mx-auto max-w-7xl px-5 pt-20 sm:px-6"><h2 className="text-2xl font-black">More EDN products</h2><div className="mt-6 flex flex-wrap gap-3">{products.filter(x => x.slug !== product.slug).map(x => <Link key={x.slug} to={`/products/${x.slug}`} className="rounded-full border border-slate-200 px-5 py-3 text-sm font-bold hover:border-emerald-500 hover:text-emerald-700">{x.name}</Link>)}</div></section>
  </div>;
};
